package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import java.util.List;

@RestController    // This means that this class is a Controller
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private Earth_PersonRepository earth_personRepository;
    private UserRepository userRepository;




    @RequestMapping("/getPerson")
    public Earth_Person earth_person(@RequestParam(value="id", defaultValue="4") Long id) {
        return earth_personRepository.findOne(id);


    }

    @GetMapping(path="/allPersons")
    public @ResponseBody Iterable<Earth_Person> getAllPersons() {
        // This returns a JSON or XML with the users
        return earth_personRepository.findAll();
    }


    @RequestMapping(value = "/person", method = RequestMethod.GET)
    public ModelAndView person() {
        return new ModelAndView("myForm", "command", new Earth_Person());
    }
    @RequestMapping(value = "/addPerson", method = RequestMethod.POST)
    public String addEarth_Person(@ModelAttribute("SpringWeb")Earth_Person earth_person,

                                  ModelMap model) {
        model.addAttribute("name", earth_person.getName());
        model.addAttribute("age", earth_person.getAge());
        model.addAttribute("song", earth_person.getSong());
        model.addAttribute("ethnicity", earth_person.getEthnicity());
        earth_personRepository.save(earth_person);


        return "result";
    }


    @RequestMapping(value = "/login", method = RequestMethod.GET)
    public ModelAndView getLoginView() {

        //return back to index.jsp
        ModelAndView model = new ModelAndView("login");

        return model;

    }

}